background #181212
foreground #ece0df
cursor #ffb2b7
selection_background #cc868b
selection_foreground #532127

color0 #353434
color1 #ff5265
color2 #ffbcab
color3 #ffdfda
color4 #b3a2d5
color5 #ef8f9d
color6 #ffba93
color7 #efd2cd
color8 #b49e9b
color9 #ff848a
color10 #ffd4c9
color11 #fff1ef
color12 #dcbc93
color13 #fea7b1
color14 #ffd1c0
color15 #ffffff

background_opacity 0.78
font_family JetBrains Mono Nerd Font
font_size 12.0
cursor_shape beam
cursor_beam_thickness 1.5
scrollback_lines 10000
