$background = 130c0d
$onBackground = f8e0e0
$surface = 130c0d
$surfaceDim = 130c0d
$surfaceBright = 372929
$surfaceContainerLowest = 000000
$surfaceContainerLow = 1a1112
$surfaceContainer = 211717
$surfaceContainerHigh = 281d1d
$surfaceContainerHighest = 302223
$onSurface = f8e0e0
$surfaceVariant = 302223
$onSurfaceVariant = bba6a7
$outline = 847172
$outlineVariant = 544445
$inverseSurface = fff8f7
$inverseOnSurface = 5d5353
$shadow = 000000
$scrim = 000000
$surfaceTint = f7b6ba
$primary = f7b6ba
$primaryDim = e8a8ac
$onPrimary = 603337
$primaryContainer = 754549
$onPrimaryContainer = ffdbdc
$inversePrimary = 845155
$primaryFixed = fab8bc
$primaryFixedDim = ebabaf
$onPrimaryFixed = 4b2126
$onPrimaryFixedVariant = 6d3d41
$secondary = e6bdbe
$secondaryDim = d7afb1
$onSecondary = 55393a
$secondaryContainer = 503436
$onSecondaryContainer = deb5b7
$secondaryFixed = ffdadb
$secondaryFixedDim = f4cacc
$onSecondaryFixed = 54383a
$onSecondaryFixedVariant = 735355
$tertiary = ffe3f7
$tertiaryDim = ffcef6
$onTertiary = 704a6b
$tertiaryContainer = ffcef6
$onTertiaryContainer = 674262
$tertiaryFixed = ffcef6
$tertiaryFixedDim = f0c0e7
$onTertiaryFixed = 52304f
$onTertiaryFixedVariant = 714c6c
$error = f97758
$errorDim = c44f34
$onError = 450900
$errorContainer = 85230a
$onErrorContainer = ff9b82
$primaryPaletteKeyColor = 9f686c
$secondaryPaletteKeyColor = 916e70
$tertiaryPaletteKeyColor = 936a8d
$neutralPaletteKeyColor = 807474
$neutralVariantPaletteKeyColor = 867373
$errorPaletteKeyColor = c75236
$primary_paletteKeyColor = 9f686c
$secondary_paletteKeyColor = 916e70
$tertiary_paletteKeyColor = 936a8d
$neutral_paletteKeyColor = 807474
$neutral_variant_paletteKeyColor = 867373
$term0 = 353434
$term1 = ff5265
$term2 = ffbcab
$term3 = ffdfda
$term4 = b3a2d5
$term5 = ef8f9d
$term6 = ffba93
$term7 = efd2cd
$term8 = b49e9b
$term9 = ff848a
$term10 = ffd4c9
$term11 = fff1ef
$term12 = dcbc93
$term13 = fea7b1
$term14 = ffd1c0
$term15 = ffffff
$rosewater = ffeeed
$flamingo = fed9da
$pink = ffd2d9
$mauve = ffa7c1
$red = ff95a2
$maroon = f8aab0
$peach = ffbdba
$yellow = ffedea
$green = ffd8c5
$teal = ffdb94
$sky = ebd1ff
$sapphire = f2b2f2
$blue = fda0cd
$lavender = ffb9d4
$klink = bf6ba0
$klinkSelection = bf6ba0
$kvisited = cb5b7e
$kvisitedSelection = cb5b7e
$knegative = ec5066
$knegativeSelection = ec5166
$kneutral = ff8884
$kneutralSelection = ff8884
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = f8e0e0
$subtext1 = bba6a7
$subtext0 = 847172
$overlay2 = 746364
$overlay1 = 635354
$overlay0 = 534647
$surface2 = 443839
$surface1 = 352a2b
$surface0 = 241b1c
$base = 130c0d
$mantle = 130c0d
$crust = 120b0c
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
