[General]
#################### General ####################

ScreenWidth="2016"
ScreenHeight="1260"
ScreenPadding="0"

Font="KogniGear"
FontSize="12"

KeyboardSize="0.4"

RoundCorners="1"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd, d MMMM"

HeaderText=""

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/lain2.jpg"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.0"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

HeaderTextColor="#8C7B6A"
DateTextColor="#8C7B6A"
TimeTextColor="#D4C9B5"

FormBackgroundColor="#1C1612"
BackgroundColor="#0E0C09"
DimBackgroundColor="#0E0C09"

LoginFieldBackgroundColor="#2E2620"
PasswordFieldBackgroundColor="#2E2620"
LoginFieldTextColor="#D4C9B5"
PasswordFieldTextColor="#D4C9B5"
UserIconColor="#8C7B6A"
PasswordIconColor="#8C7B6A"

PlaceholderTextColor="#5A5048"
WarningColor="#A08060"

LoginButtonTextColor="#1C1612"
LoginButtonBackgroundColor="#D4C9B5"
SystemButtonsIconsColor="#8C7B6A"
SessionButtonTextColor="#8C7B6A"
VirtualKeyboardButtonTextColor="#8C7B6A"

DropdownTextColor="#D4C9B5"
DropdownSelectedBackgroundColor="#8C7B6A"
DropdownBackgroundColor="#2E2620"

HighlightTextColor="#1C1612"
HighlightBackgroundColor="#D4C9B5"
HighlightBorderColor="#8C7B6A"

HoverUserIconColor="#D4C9B5"
HoverPasswordIconColor="#D4C9B5"
HoverSystemButtonsIconsColor="#D4C9B5"
HoverSessionButtonTextColor="#D4C9B5"
HoverVirtualKeyboardButtonTextColor="#D4C9B5"

#################### Form ####################

PartialBlur="false"
FullBlur="false"
BlurMax="10"
Blur="0.5"

HaveFormBackground="true"
FormPosition="right"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="true"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="true"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

#################### Translation ####################

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
